name: OpenAISampleApp
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_5
  - ca-certificates=2024.3.11=haa95532_0
  - expat=2.5.0=hd77b12b_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=3.0.13=h2bbff1b_0
  - pip=23.3.1=py312haa95532_0
  - python=3.12.2=h1d929f7_0
  - setuptools=68.2.2=py312haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2024a=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py312haa95532_0
  - xz=5.4.6=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - -r requirements.txt
